library(idealImmunoTP)
library(airway)

library(DESeq2) 
library(SummarizedExperiment) 
library(GenomicRanges) 
library(IRanges)
library(S4Vectors) 
library(ggplot2) 
library(heatmaply)
library(plotly)
library(pcaExplorer) 
library(IHW) 
library(gplots) 
library(UpSetR) 
library(goseq) 
library(stringr) 
library(dplyr)
library(limma) 
library(GOstats) 
library(GO.db) 
library(AnnotationDbi) 
library(shiny)
library(shinydashboard) 
library(shinyBS) 
library(DT) 
library(rentrez) 
library(rintrojs) 
library(ggrepel) 
library(knitr)
library(rmarkdown) 
library(shinyAce) 
library(BiocParallel) 
library(grDevices) 
library(base64enc)
library(methods)
library(testthat) 
library(BiocStyle) 
library(airway) 
library(org.Hs.eg.db)
library(TxDb.Hsapiens.UCSC.hg38.knownGene) 
library(DEFormats) 
library(edgeR)

load(file = "testData.RData")

idealImmunoTP(dds_obj = dds_airway, annotation_obj = annotation_airway, res_obj = res_airway)
